name: coin_id
description: Rare Coin Identifier & Valuation Tool.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Factory Standard Core
  go_router: ^12.0.0
  flutter_riverpod: ^2.4.0
  google_fonts: ^6.3.2

  # Feature Dependencies
  tflite_flutter: ^0.10.1
  image: ^4.0.17
  camera: ^0.10.5
  http: ^1.1.0
  intl: ^0.18.1
  permission_handler: ^11.0.1

  # Factory Modules
  ui_shell:
    path: ../../modules/ui_shell
  analytics_wrapper:
    path: ../../modules/analytics_wrapper
  onboarding_manager:
    path: ../../modules/onboarding_manager

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "../../assets/master_icon.png"

flutter_native_splash:
  color: "#121212"
  image: "../../assets/master_icon.png"
  android_12:
    image: "../../assets/master_icon.png"
    icon_background_color: "#121212"

flutter:
  uses-material-design: true
