name: coin_id
description: Rare Coin Identifier & Valuation Tool.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Factory Standard Core
  go_router: ^12.0.0
  flutter_riverpod: ^2.4.0
  google_fonts: ^6.3.2

  # Feature Dependencies
  tflite_flutter: ^0.10.1
  camera: ^0.10.5
  http: ^1.1.0
  intl: ^0.18.1
  permission_handler: ^11.0.1

  # Factory Modules
  ui_shell:
    path: ../../modules/ui_shell
  analytics_wrapper:
    path: ../../modules/analytics_wrapper

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
