name: Reusable iOS Build

on:
    workflow_call:
        inputs:
            working_directory:
                required: true
                type: string
                description: "Path to the app (e.g. apps/coin_id)"
            build_name:
                required: true
                type: string
                description: "Name of the artifact (e.g. coin-id-ios)"

jobs:
    build-ios:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v3

            - uses: subosito/flutter-action@v2
              with:
                  channel: "stable"

            - name: ğŸ“¦ Install Dependencies
              working-directory: ${{ inputs.working_directory }}
              run: flutter pub get

            - name: ğŸ› ï¸ Build iOS (No Codesign)
              working-directory: ${{ inputs.working_directory }}
              # Building 'ios' creates a .app runner. We need to zip it like a fake .ipa for now.
              run: |
                  flutter build ios --release --no-codesign
                  mkdir -p Payload
                  mv build/ios/iphoneos/Runner.app Payload
                  zip -r ${{ inputs.build_name }}.ipa Payload

            - name: ğŸ“¤ Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ inputs.build_name }}-ipa
                  path: ${{ inputs.working_directory }}/${{ inputs.build_name }}.ipa
