name: period_tracker
description: Privacy-First Secure Cycle Tracker.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Factory Standard Core
  go_router: ^12.0.0
  flutter_riverpod: ^2.4.0
  google_fonts: ^6.3.2

  # Feature Dependencies
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  flutter_secure_storage: ^9.0.0
  table_calendar: ^3.0.9
  intl: ^0.18.1
  path_provider: ^2.1.1

  # Factory Modules
  ui_shell:
    path: ../../modules/ui_shell
  analytics_wrapper:
    path: ../../modules/analytics_wrapper

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  isar_generator: ^3.1.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
